server:
    port: 8080
    servlet.context-path: /mall
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
            prefix: /web
            suffix: .jsp
    
mybatis:
    mapperLocations: classpath:com/situ/mall/**/*.xml
    typeAliasesPackage: com.situ.mall.cart.model,com.situ.mall.order.model,com.situ.mall.product.model,com.situ.mall.sys.model

#打印SQL语句    
#logging:
#    level: 
#      com.situ.mall.sys.mapper: debug
    